title: frederative
description: generative artist exploring nature-based algorithms
#theme: just-the-docs
remote_theme: "pmarsceill/just-the-docs"

color_scheme: dark

url: https://frederative.github.io

#aux_links:
#  twitter: https://twitter.com/frederative
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
nav_external_links:
  - title: twitter
    url: https://twitter.com/frederative
    hide_icon: true # set to true to hide the external link icon - defaults to false
  - title: instagram
    url: https://www.instagram.com/frederative_art/
    hide_icon: true

callouts:
  warning:
    title: warning
    color: red

  note:
    title: note
    color: green

  tutorial-img:
    title:
    color: green
